[general]
filename = taskell.md

[layout]
padding = 1
column_width = 30
column_padding = 3
description_indicator = "≡"
statusbar = true

[markdown]
title = "##"
task = "-"
summary = "    >"
due = "    @"
subtask = "    *"
localTimes = false

[github]
; token = ${GITHUB_TOKEN}

